### ISSUE TITLE
Configure connection attempts by unknown peers

### ISSUE THREAD

**Issue by rubo77** [ffnord/ffnord-puppet-gateway#133]
after this line:

[`include peers from "peers"`](https://github.com/ffnord/ffnord-puppet-gateway/blob/master/templates/etc/fastd/fastd.conf.erb#L14)

 we could add:

    # Configure connection attempts by unknown peers
    # "true" means, all attempts are accepted or a shell command that is run on attempts
    on verify "true";
    #on verify "/bin/bash /path/to/fastd/verify.sh $PEER_KEY";

Optionally configure this in your gateway.pp

**Comment by ohrensessel** [comment]
we don't support this approach here in hamburg, only nodes that are present
in our key repository (= are signed up) are allowed to connect

2015-09-07 10:12 GMT+02:00 Ruben Barkow <notifications@github.com>:

**Comment by do9xe** [comment]
As we plan to addapt the community in flensburg to one of our gateways with the multi-community-setup we need this feature. Flensburg went to accept-all in the fall of 2014 and i don't remember if they kept any kind of record of the registred keys.
If this issue is a problem for all people, which are participating in this project we are going to change the flensburg-specific fastd.conf by hand.

**Comment by rubo77** [comment]
We would only need a flag, that would add this line or not:

    on verify "true";

if it is not present, then the default behaviour is that only keys from the peers folder are accepted like in kiel and hamburg

**Comment by ohrensessel** [comment]
if this is an option (with the default value in a way that nothing changes
for hamburg) it would be totally fine with me.

2015-09-07 11:17 GMT+02:00 Ruben Barkow <notifications@github.com>:
