### ISSUE TITLE
Allow to disable unwanted modules like bird and tinc

### ISSUE THREAD

**Issue by do9xe** [ffnord/ffnord-puppet-gateway#67]
As already diskussed we should add the possibility to stop puppet from installing tinc, bird and bird6 on a server. This option should be configurable in the gateway.pp.
Some Communitys don't use all modules like Kiel an Flensburg.<br>

example:<br>
bird => true<br>
bird6 => false<br>
tinc => true <br>

**Comment by wusel42** [comment]
I'd like to second this for Gütersloh & Müritz ;)

**Comment by ohrensessel** [comment]
since c41ac6e9ec9be5b366af10287ecff9fc026722dc there is the possibility to exclude bird4 or bird6 via the params module [1]. of course, one of both is needed if you want to have icvpn.

for tinc: simply do not use the icvpn module.

[1] https://github.com/ffnord/ffnord-puppet-gateway/blob/c41ac6e9ec9be5b366af10287ecff9fc026722dc/manifests/params.pp#L7-L8
